### PR TITLE
Added InitGObjectsManually.

### PR DESCRIPTION
**Pull request by gir489returns**
You asked, I delivered. 🙂

### CODE REVIEW

**Comment by Fischsalat** [comment]
Please don't use Windows.h typedefs such as `PVOID`. Also what about all of the other offsets? Adding an option to override GObjects alone is pretty  useless if you need to re-dump the SDK for the other offsets anyways.

Please also keep manual-init functions an option that is only activated when explicitly set (eg. `Settings::CppGenerator::bAddManualOverridOptions == true`);

**Comment by gir489returns** [comment]
@Fischsalat I really only need GObjects from the SDK for IsA-> as it directly uses the GObjects Tarray. However, I can add those.

Seems kinda ass backwards that you mandate the usage of the MSVC toolchain but reject MSVC-specific header usages, but OK. I'll change that too.

**Comment by gir489returns** [comment]
Offsets::ProcessEvent doesn't seem to be used anymore. It uses Offsets::ProcessEventIdx to virtual call ProcessEvent. GObjects and AppendString are really the only two things that actually use Offsets.

**Comment by Fischsalat** [comment]
> I really only need GObjects from the SDK for IsA

For IsA you also need AppendString/GNames/ToString, because `UObject::StaticClass()` needs to find the class by name. \
*Also as a small sidenote: GObjects isn't a TArray anymore since UE4*

> Seems kinda ass backwards that you mandate the usage of the MSVC toolchain but reject MSVC-specific header usages

Well, first of all I appreciate the kind words. Not using PVOID is less a question of platform-specific (not toolchain-specific) headers, but more of a code-style guideline.

> Offsets::ProcessEvent doesn't seem to be used anymore

Offsets::ProcessEvent was never used, I added that to `Offsets` for quick navigation to ProcessEvent in IDA or Reclass.

Ok, lets get back to the actual pull request, I appreciate that you changed the type and added an override function for AppendString. However, the override for AppendString doesn't work if the SDK is using GNames, as the `InitManually(void* AppendStringParameter)` doesn't cast the parameter to the correct type when doing the assignment.

Please fix this issue and test the generator on a few different games to make sure your override functions work with AppendString/GNames.

**Comment by gir489returns** [comment]
@Fischsalat I made the changes you requested but am not sure of which games use GNames. I only have Palworld (UE5), Ready or Not (UE4.27.1) and Robocop Rogue City (UE5). All 3 of them use AppendString. Can you tell me which game uses GName so I can test it?

**Comment by Fischsalat** [comment]
You can force GNames in FName::Init.

**Comment by gir489returns** [comment]
> You can force GNames in FName::Init.

Thanks. I'm currently dealing with a drive crash. I lost all of the stuff on my D drive (giggidy) that wasn't backed up onto OneDrive. 90% of it was just games that I have to redownload from steams, as all my source code and IDA databases were on OneDrive. I got a new SSD this morning and it's currently repopulating.

Anyway, after that's done I'll get back to testing this. Is the code in its current state acceptable, minus testing?

**Comment by Fischsalat** [comment]
Well that sounds annoying. The code quality seems goo as of right now.

**Comment by gir489returns** [comment]
@Fischsalat Not to get off topic, but I think I opened a can of worms on several projects I'm on thanks to you.

Here's the rundown: TUObjectArrayWrapper's -> operator uses the [[unlikely]] declerator. During my hack's migration from Clang to MSVC's Latest, we had several discussions on (YO WHAT THE FUCK HAVE YOU SEEN THIS?!) and that propigated to several other projects I'm working on too, not just Unreal. We are now in the process of refactoring all of our code to use likely/unlikely declarators when applicable. 

Right, so why am I tell you? Well, you use it in TUObjectArrayWrapper, but not FName which I discovered when testing (still in progress BTW) your request of GName/FName interoperability.

Is there a reason why you don't use [[unlikely]] here?

**Comment by gir489returns** [comment]
I got around to testing this.

Using the following signatures:

FName::Append:

image

```
if (auto fname_append_string = PatternScanner::Scan("E8 ? ? ? ? 49 63 C7 48 8B DE 48 8D 3C C6")) [[likely]]
{
    SDK::FName::InitManually(fname_append_string.GetCall().To<PVOID>());
}
else [[unlikely]]
{
    MessageBox(NULL, L"FName::AppendString Signature Not Found", L"ERROR", MB_ICONERROR | MB_OK);
}
```

image

GNames:

```
if (auto gnames = PatternScanner::Scan("E8 ? ? ? ? 49 63 C7 48 8B DE 48 8D 3C C6")) [[likely]]
{
    SDK::FName::InitManually(gnames.GetRef(3).To<PVOID>());
}
else [[unlikely]]
{
    MessageBox(NULL, L"FName::AppendString Signature Not Found", L"ERROR", MB_ICONERROR | MB_OK);
}
```

Everything seemed fine in both cases. It compiled and ran and did not crash.

**Pull request merged**
